### ISSUE TITLE
Where to apply condition

### ISSUE THREAD

**Issue by syedali1621** [derenlei/Unity_Detection2AR#18]
I am using yolov2tiny my own model and i want to show 3d model when it detects specific class. Could you describe where to put if condition. My model is train on 3 classes i need to show 3 different 3d models when it detect each class. For example when it detect class 1 i need to show class 1 3d model, when it detect class 2 then class 2 3d model and same case for class 3.

Thank you

**Comment by derenlei** [comment]
Hi @syedali1621, 
I think you could anchor your 3d models here: https://github.com/derenlei/Unity_Detection2AR/blob/main/Assets/Scripts/AnchorCreator.cs#L50. 
Labels could be accessed through `outline.Label`.

**Comment by syedali1621** [comment]
@derenlei Thank you i used outline.label to apply if condition but in PhoneARCamera script.
