### ISSUE TITLE
Show bounding box on detected object instantly

### ISSUE THREAD

**Issue by syedali1621** [derenlei/Unity_Detection2AR#19]
I am using yolov2tiny my own model i want to detect object from far and near distance but current project is not detecting from far distance and also it need to hold the phone for few seconds to detect from near distance. I want instance detection could you please guide which script do i need to modify. My same model is detecting well on tfunity below project it is detecting from far and near distance instantly with bounding box i need same behavior in this project.

https://github.com/shaqian/TF-Unity-ARFoundation
Thank you.

**Comment by derenlei** [comment]
Hi @syedali1621. You can use a lower confidence threshold for your model at https://github.com/derenlei/Unity_Detection2AR/blob/main/Assets/Scripts/DetectorYolo2.cs#L30.
