### ISSUE TITLE
Try a different yolo model but not working

### ISSUE THREAD

**Issue by marcomameli1992** [derenlei/Unity_Detection2AR#2]
Dear, I'm trying to use a YOLO-v2 tiny from [onnx model zoo](https://github.com/onnx/models) and I change the name of input and output in the Detector script bu the model does not work. 
Analyzing the model I see there are some differences, like constants and number of weights. Can you share your yolo configuration to obtain the same model with my train data?

**Comment by derenlei** [comment]
Hi,

The YOLO-v2 tiny configuration we used for training can be found in the darknet repo: [https://github.com/pjreddie/darknet/blob/master/cfg/yolov2-tiny.cfg](https://github.com/pjreddie/darknet/blob/master/cfg/yolov2-tiny.cfg)

We used darknet to train the model and then converted it to onnx format. (darknet -> tensorflow -> freeze -> onnx)

**Comment by L0GI0** [comment]
Hey, we also tried to use some yolov2-tiny models, some work, some doesn't, we are trying to figure out what is the cause, is it is about the .cfg file, that means if a model uses different one, then it cant be use in this project ? Or maybe we can somehow configure the project in unity and run any yolo2-tiny model ?

**Comment by ROBYER1** [comment]
> Hey, we also tried to use some yolov2-tiny models, some work, some doesn't, we are trying to figure out what is the cause, is it about the .cfg file ? That means if a model uses different one, then it cant be use in this project ? Or maybe we can somehow configure the project in unity and run any yolo2-tiny model ?

Did you make sure to change the input and output variables in the Detector.cs script to match those of your model?

Are you getting any errors?
