### ISSUE TITLE
Anchors Facing The Camera

### ISSUE THREAD

**Issue by KracelKany** [derenlei/Unity_Detection2AR#23]
Is there a way to make the Anchors face the camera all the time?
I don't seem to find the way to do it.

**Comment by derenlei** [comment]
Hi @KracelKany,

You could attach this script to your anchor: https://github.com/derenlei/Unity_Detection2AR/blob/main/Assets/Scripts/NewText.cs.
It's already attached to the Text Anchor example.

**Comment by KracelKany** [comment]
Thank you very much! I don't remember if the Text Box in the hieararchy used it, because I deleted from there and using only from prefabs and that one didn't have it. 
Do you have some insights/hints on where to start if I want to change the Text anchor to show some description of the object triggered by a canvas button? Or should I start a new issue? I am quite new to GitHub.

**Comment by KracelKany** [comment]
> Do you have some insights/hints on where to start if I want to change the Text anchor to show some description of the object triggered by a canvas button? Or should I start a new issue? I am quite new to GitHub.

I figured it out.
