### ISSUE TITLE
No active UnityEngine.XR.ARSubsystems.XRSessionSubsystem is available (Warning)

### ISSUE THREAD

**Issue by L0GI0** [derenlei/Unity_Detection2AR#3]
![image](https://user-images.githubusercontent.com/48987014/98484537-89b39180-2210-11eb-9a69-24a7f075e34c.png)

Hello Sir, do you mby know solution to these warning ? 
Initialize XR on Startup  is checked, but there is no  ARCamera option in Plug-in providers, if enabling it should be done there.

![image](https://user-images.githubusercontent.com/48987014/98484598-11010500-2211-11eb-92ab-5c392ae4dc9d.png)

Thanks for your time and sharing your project ;D

**Comment by L0GI0** [comment]
Also, can u mby somehow use laptop web cam camera and play this project in Unity ?
Thank you,
BR.

**Comment by BeiieB** [comment]
Hi,
I built the project on an Android phone but didn't see those warnings.
If you are getting a black screen on Android, try the following steps:
1. Check **ARCore** in Plug-in Providers.
![image](https://user-images.githubusercontent.com/23055895/99159875-b72b8f80-2695-11eb-9960-b5672b31ea94.png)
2. Set Project Settings -> Player -> Other Settings -> Minimum API Level to **API Level 24**.
3. Enable **Auto Graphics API**
![image](https://user-images.githubusercontent.com/23055895/99159905-1f7a7100-2696-11eb-8127-849321f660b8.png)
It works fine on my Android phone.

**Comment by L0GI0** [comment]
Thank you, that help to successfully build and run the project.
