### ISSUE TITLE
Minimum API Level 

### ISSUE THREAD

**Issue by djebel-amila** [derenlei/Unity_Detection2AR#4]
Hi, thank you for this brilliant demo. 
Maybe add an instruction to set “**Project Settings > Player > Others Settings > Minimum API Level**” to “**Android 7.0 'Nougat' (API Level 24)**“. I got an error on build and changed it, but it may not be obvious for some users. Cheers.

**Comment by derenlei** [comment]
Hi. Thanks! I'll add an instruction to set the Minimum API Level. Cheers.
