### ISSUE TITLE
Does this work with moving objects?

### ISSUE THREAD

**Issue by ROBYER1** [derenlei/Unity_Detection2AR#5]
Not really an issue, I am just investigating open-source object detection methods and wondered if this can re-localise once an object has moved or localise in a more 'real time' way if the object is moving?

**Comment by derenlei** [comment]
Hi,

That's a very cool and useful feature. I think it's doable but depends on what kind of scenario you are aiming at.

**What is hard to do:** If you would like to keep track of several objects of the same type (e.g. people hanging around in a mall), there are certain object tracking algorithms you could try, but unfortunately, it will be a very hard problem to solve using an object detection model in this project.

**Why:** At the current stage, this project uses a detection model to recognize objects at every single frame. It doesn't use any machine learning approaches to keep track of recognized objects. Instead, it tries to identify whether two recognized objects at different frames (time steps) are the same one through engineering approaches (e.g. whether the positions of two bouding boxes are similar).

**What you can do:** To keep track of a slightly moving object, you can just keep the detection model running in the backend and re-localize the object periodically.

Hope it helps.

**Comment by ROBYER1** [comment]
In my use case I am working on detecting a single object, so this is very useful thankyou! Closing this issue 👍
