### ISSUE TITLE
Android: Anchor is always offset quite far from detected object

### ISSUE THREAD

**Issue by ROBYER1** [derenlei/Unity_Detection2AR#7]
I know you mentioned you would look into fixing this already, just recording it here

On Android with ARCore (using Sony Xperia XZ3 for my tests), the anchors placed on detection are always at least 30cm out from the detected object when the anchor is placed. This behaviour is consistent on android in my tests with different dishes.
![Screenshot_20201202-231240](https://user-images.githubusercontent.com/10745594/101142054-00c02800-360d-11eb-8fd5-cf8cfac332a0.png)
![Screenshot_20201202-170552](https://user-images.githubusercontent.com/10745594/101142060-0289eb80-360d-11eb-933c-03ac4a510fd6.png)

**Comment by derenlei** [comment]
Hi,

I have pushed a simple fix here 59547cdafb1a7ab3c3985f5db11f0c08d27b963e.

Roughly scan the surrounding area before placing the anchor will help improve localization. In addition to that, iOS usually performs better than android.

Hope it helps.

**Comment by ROBYER1** [comment]
Hi Deren

Those are good tips, your latest fix push didn't do it but I found the Anchor script was only looking for planes, the reason the markers weren't spot on was because it was raycasting only to planes, not feature points
https://github.com/derenlei/Unity_Detection2AR/pull/8
