### ISSUE TITLE
How to get this working with Yolo v3-tiny?

### ISSUE THREAD

**Issue by ROBYER1** [derenlei/Unity_Detection2AR#9]
So I used AlexeyAB's Darknet fork to train a custom model using Yolo-v3-tiny making my own weights from scratch to make a detector for apples/oranges as a quick test. 

I used this guide to convert my model to onnx
https://github.com/jkjung-avt/tensorrt_demos#demo-5-yolov4

Apparently there is an issue with yolov3 tiny import in Unity Barracuda 1.2.0 preview and above
Unity-Technologies/barracuda-release#122

I can't seem to get the model to work in your project, using Barracuda preview 1.2.0 and using my names file + modifying Detector.cs to read the input and one of the outputs.

Here is the link to my onnx file, some test images and the names file https://drive.google.com/file/d/1uY81Gh2Edh63R7G_6i5KI_oVLdMCuiem/view?usp=sharing

Any help or direction on why the Yolo v3 onnx model doesn't work would be great, I'm still investigating.

**Comment by ROBYER1** [comment]
Apparently there is an issue with yolov3 tiny import in Unity Barracuda 1.2.0 preview and above
https://github.com/Unity-Technologies/barracuda-release/issues/122

**Comment by ROBYER1** [comment]
I am thinking my issue may be when I get the input and output node names for the graph after converting to TF using DW2TF, I get 1 input but 2 output names. I was expecting 1 input 1 output 🧐

**Comment by ROBYER1** [comment]
The exported onnx graph vs the original cfg file:

![yolov3-tiny-darkmarktest-416 cfg](https://user-images.githubusercontent.com/10745594/102783018-3e091180-4392-11eb-8e89-caf718b490f7.png)
![yolov3-tiny-darkmarktest-416 onnx](https://user-images.githubusercontent.com/10745594/102783026-3f3a3e80-4392-11eb-842f-52aaa0707749.png)
![102714630-dab2ad00-42c7-11eb-9ba1-0b7479b40287](https://user-images.githubusercontent.com/10745594/102783075-4f521e00-4392-11eb-904f-27aedbd9c560.png)

**Comment by ROBYER1** [comment]
After some investigation, I have found that the Yolo v3 tiny inputs/outputs are different to v2-tiny quite a bit which is why the v3 tiny model isn't working with Detector.cs

I have seen that Detector.cs follows [this Microsoft C# example](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx#create-the-parser) very closely which was made for Yolo-v2-tiny, however they have not updated or modified the sample to show how to parse a Yolo-v3-tiny model.

I am very interested in using the Yolo-v3-tiny model in this project if possible and can help but I am not very experienced in writing onnx model parsers in C#, I am however very proficient in Unity programming and AR development.

Please let me know if I can help update this repo for v3-tiny!

**Comment by derenlei** [comment]
Hi @ROBYER1, it would be great if you could help to support Yolo-v3-tiny for the detector!

Barracuda didn't support Yolo-v3 or v4 the last time I checked (September?). 

Here are the Barracuda supported ONNX operators. I think it's related. https://docs.unity3d.com/Packages/com.unity.barracuda@1.0/manual/SupportedOperators.html

**Comment by ROBYER1** [comment]
> Hi @ROBYER1, it would be great if you could help to support Yolo-v3-tiny for the detector!
> 
> Barracuda didn't support Yolo-v3 or v4 the last time I checked (September?).
> 
> Here are the Barracuda supported ONNX operators. I think it's related. https://docs.unity3d.com/Packages/com.unity.barracuda@1.0/manual/SupportedOperators.html

Hey, this was added in [Barracuda](https://docs.unity3d.com/Packages/com.unity.barracuda@1.2/changelog/CHANGELOG.html) 1.2.0 preview package. You can find the preview packages using the instructions here to un-hude them in package manager https://docs.unity3d.com/2020.1/Documentation/Manual/class-PackageManager.html

I am currently looking into this but I'm more experienced with Unitt AR development and C# programming than I am with reading python or understanding how to get values in/out of Darknet Yolo models!

I got some interesting discussion going with Unity Barracuda team [here](https://github.com/Unity-Technologies/barracuda-release/issues/122#issuecomment-749244073) about how they could use some examples of how to use these models in Unity and get inputs/outputs from them.

Are you available if I need any pointers or assistance with upgrading this to Yolo v3 tiny? I'd really appreciate any help or tips as I'm still very new to ML in general.

**Comment by ROBYER1** [comment]
@derenlei I made some progress with v3, will push to [my fork](https://github.com/ROBYER1/Unity_Detection2AR) shortly. 

I am getting the correct classes + predictions, however I barely ever see a bounding box, if I do it is a small line across the screen + the GetConfidence calculation in Detector.cs seems to be causing issues and I'm not sure what is going wrong with the 'Sigmoid' calculation I have left unchanged. I had to set the threshold very low to see any anchors placed and most of the time they were low like 5%.

You can see in #1 That I get the class Apple at 0.998, which sounds spot on

#2 Okay so as soon as we go to get the top score, the confidence value is always really low

#3 The bounding box dimensions are all minus values

![see](https://user-images.githubusercontent.com/10745594/103088652-60459e00-45e3-11eb-84ea-141a36bc8ddc.jpg)

**Comment by ROBYER1** [comment]
Merry Christmas! I got the top results coming in which means things are.. sort of working (woo!) but the values for confidence are wrong and the bounding boxes have minus values so I never see them, they are inverted or they are wildly off screen.

I'm finding the 0% results quite amusing but to get them I had to set the threshold/minimum confidence to 0.001 to even see those results otherwise it never detects anything.

I'm really stuck at this point

![girafee](https://user-images.githubusercontent.com/10745594/103100644-736c6400-460b-11eb-8f4b-e052359cd3e1.JPG)
![birb](https://user-images.githubusercontent.com/10745594/103100646-75362780-460b-11eb-9ec8-3f6ff83198c0.JPG)

**Comment by ROBYER1** [comment]
I am using this converter for converting Darknet Yolo v3 tiny to ONNX but there are some issues with the converted mAP accuracy of the onnx files vs the original darknet results
Issues to  track:
https://github.com/jkjung-avt/tensorrt_demos/issues/315
https://github.com/isarsoft/yolov4-triton-tensorrt/issues/7

**Comment by derenlei** [comment]
Update tiny Yolo3 support in #12
